runtime init/basic.vim
runtime init/plugins.vim
runtime init/color.vim
runtime init/keymap.vim
runtime plugins/completion-config.vim
runtime plugins/rust-config.vim
runtime plugins/rust-lsp-config.vim
runtime plugins/trouble-config.vim
runtime plugins/telescope-config.vim
runtime plugins/fern-config.vim
